import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalUI from "../components/ui/GlobalUI";


export const metadata = {
  title: "Bugs Want Us",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GlobalUI />
        {children}
      </body>
    </html>
  );
}
